# SPDX-FileCopyrightText: 1997 Argonne National Laboratory
#
# SPDX-License-Identifier: EPICS

TOP=..

include $(TOP)/configure/CONFIG
include $(TOP)/configure/CONFIG_SITE
include $(RULES)/configure/RULES_DIRS
